### ISSUE TITLE
SSH Key, office mac

### ISSUE THREAD

**Issue by clemekay** [ZanderUF/GamesLabUF#10]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPpoDgSo/74i7P/qnUlY1tN5LU1fUBtVTDb6RUM4YmLE1LE5REj0gm8SpUgbkud6x2C5ziFmYPVJZG1NqESeGshH5aikBndvR9tLzsPOuMXxelJER9m+48krWiiZ4XRgXO2neX1cBN06Z5pCmk6vMaqfw6UP1CKmA2sNvJCoCNp9ykyJ/vBZqTpBWIVDlVwiOk86Q2PgCilyo9+dLw2nKat5h69L6pneDZOR/+KiLH3BgIVXjIe12CJ8c29iqWnkyiSEECvUxvf1DCY7QB+W2d3kJougnOkU3+N/xl77ao/i4E0K6TrjpC5CERWpDTlUIbgpmCLUSP8q2saT0G+gXhvYqT9NwcBYOQqKbWH8o7p+Bi4/k0N+i08D7vnDVJoEuhanwsUDBPefWvHonHLm50TDjo032Vw6lpUeaogm4aFR2pYlUus/C3D+GeLqQTZhFUzPyPWPn5SMEw22K27ru1+d3wef5jKvJRCCCqevRuy7pPK+kE1gSx1c8g4rCo22Yj2yI5EXq71NVLsIe2JgV/5cgwIi5qbrFtSIBzIOEZuDp6qRbLZQop0VilXSt45KTa8YMPEx4Dfh+bgEFTuYY1J5m2+j+cz6rHViksXDjbA+9jepXuk3mbuW/k2crEim0wXfdIrxj33jPZRA4Hcfz/U4i27P/03BVwa1KwlH5FxQ== clementsk97@gmail.com

**Comment by ZanderUF** [comment]
I added this to the T-ReX GitHub repo.
