### ISSUE TITLE
pmc missing?

### ISSUE THREAD

**Issue by goluoglu** [ZanderUF/GamesLabUF#3]
/projects/trex/SCALE6.2.2/packages/Ampx/irffactor/ComputeShieldedXSs_M.f90(16): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [PMC_M]
      use pmc_M

**Comment by ZanderUF** [comment]
Are you building the packages individually? or just doing a 'make' right away?

**Comment by ZanderUF** [comment]
I would consider having these issues be opened on the 'trex' https://github.com/ZanderUF/trex/issues 
page, since it is private and this GitHub repo is not.

**Comment by ZanderUF** [comment]
I have setup the repo to include everything so pmc should be there now.
