### ISSUE TITLE
Public ssh key for my macbook air

### ISSUE THREAD

**Issue by RachelSuzan** [ZanderUF/GamesLabUF#4]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwsD9OrPEKj+G7Oni/BXNMb5ojbUT/2Y2awVe/WaxN+/X8U1/Cy7OG8MWmUVmCNrpM8wO5RF6nJYHFNpAvwIEA0ic6M0DpX3DXtpm9aYGIed7DzNKF4eAnzlZemoLJ2i+9H0QXcb4pRGbjjJ0kvtZntjWx7Ojd6TJ47OyDLaO1AuOandOUDXu7jXurl7o1pbayW/XITQaOKoGT1VLluQrxB98ULXkZ/K8HTBgbuc7LX54yjvtCxIO8a2QYFa0K/HTRSIdLrGGHoo9i9w8MxASloYUkkg0D+VpVTvPUhQkKbRZMYfucYpEABx6oNDq2iiFT3w5Qfr7BgJTZh5cWxO69 RachelB@MacBook-Air.local

**Comment by ZanderUF** [comment]
I will add this.  Hold off on cloning this until later this afternoon. I am trying to fix one thing.
